from ScrapeSwarm.settings.base import *

# Staging specific settings
CONCURRENT_REQUESTS = 32
DOWNLOAD_DELAY = 3
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 5
AUTOTHROTTLE_MAX_DELAY = 60
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
USER_AGENT = "ScrapeSwarm - Staging"
HTTPCACHE_IGNORE_HTTP_CODES = [500, 502, 503, 504, 522, 524, 408]
HTTPCACHE_EXPIRATION_SECS = 5
