# Use an official Redis image as the base image
FROM redis:6.2-alpine

# Set the working directory
WORKDIR /usr/local/etc/redis

# Copy custom Redis configuration file to the container
COPY redis.conf .

# Expose the default Redis port
EXPOSE 6379

# Set the entrypoint command to use the custom configuration
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
